### ISSUE TITLE
Be more indicative of what went wrong inside C.

### ISSUE THREAD

**Issue by vext01** [softdevteam/hwtracer#12]
#11 is proposing a `CFailure` error variant. That's all very well but it doesn't say what went wrong within C.

Since we don't have enough exceptional values in the return value of `traceme_start_tracer` in which to encode what went wrong, and since we want this thread safe, I propose we instead put an "error number" into the tracer context which encodes what actually went wrong. Then when the error bubbles back up to Rust, we can stuff an error description inside `CFailure`, thus letting the user know what went wrong.

Thoughts? @ltratt

**Comment by ltratt** [comment]
I don't really have enough context to say anything sensible here I'm afraid.

**Comment by vext01** [comment]
Basically all C errors get collapsed to:

https://github.com/softdevteam/traceme/blob/7d2adf27bda255a3045b9760c58945ab5dffbc13/src/errors.rs#L49

With no further information.

To give better information we would need a way for C to communicate back to Rust what went wrong. I'd settle for a simple string description of what happened.

On the other hand, I'm starting to think we need to get something working before bike-shedding too much. Things don't often go wrong in the C part of the code, so it's not particularly high priority IMHO.

**Comment by vext01** [comment]
One thing we could do here is try to propagate an `errno` back to rust and stuff that inside the `CFailure` error type. This is going to mean adding one extra parameter to each C func.

However, libipt has it's own error indicator numbers, so we ideally want a way to say "this went wrong in libc" or "this went wrong in libipt". Perhaps we need a struct with an "error class" tag which is always communicated back to Rust.

**Comment by vext01** [comment]
Fixed with #56
