### ISSUE TITLE
Splitting errors?

### ISSUE THREAD

**Issue by ltratt** [softdevteam/hwtracer#25]
At the moment, this crate has a single `Error` type. This has one advantage in that we don't have zillions of different error types lurking around. It has the disadvantage that it means the error type is misleading: if (say) you start a trace and you get a PT error, do you also want to check for all the other error conditions that starting a trace can't raise? Getting a balance between the two extremes isn't completely trivial, and I don't claim to have total insight on what's best.

That said, my general preference is for functions to only return error types that they could realistically generate. That does suggest that we need more error types lurking around (occasionally to the granularity of one per function, though obviously fewer types is good when we can get away with that). The good news is that we can use from types to painlessly aggregate error types when necessary.

I suspect we should do a bit of scouting of Rust libraries to see if there's any precedent we can draw on here.

**Comment by vext01** [comment]
I tend to agree. I don't want to have a new error type for each possible function, but using one error type means we have to consider sub-errors which may never occur for a given function call.

See also #12.

**Comment by ltratt** [comment]
Agreed.
