### ISSUE TITLE
Build deps in the `OUT_DIR` so they get cleaned.

### ISSUE THREAD

**Issue by vext01** [softdevteam/hwtracer#76]
Currently a `cargo clean` will not clean the C dependencies we build since they are built outside of Cargo's view of the world. There's no `post-clean` hook for cargo, but we could build our stuff inside the OUT_DIR to ensure it gets cleaned.

**Comment by bjorn3** [comment]
Another thing is that you are not allowed to modify the source dir. I believe cargo won't even let you upload something to crates.io when it detects it.
